name: 'README updater action for TeX projects'
description: 'Update README using TeX source code'
author: 'Tarang Janawalkar'

inputs:
  GITHUB_TOKEN: 
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'lib/index.js'