name: "README CI test"
description: "CI for README using TeX source code."
author: "Tarang Janawalkar"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: align-left
  color: gray-dark
