name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  Generate-README:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          run_install: true

      - name: Update README
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}