name: Continuous Integration Workflow

on:
  push:
    branches: [master]

jobs:
  README-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 17

      - name: Install dependencies
        uses: npm ci

      - name: README CI
        uses: Tarang74/test-readme-actions@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
