name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  Generate-README:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
          
      - name: Update README
        uses: ../action.yml
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}