name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  Generate-README:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout

      - name: Use Node.js
        uses: actions/setup-node
        with:
          node-version: latest

      - name: Cache pnpm modules
        uses: actions/cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup
        with:
          run_install: true
          
      - name: Update README
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}