name: Continuous Integration Workflow

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0

      - run: npm ci
      - run: npm run build
      
  README-CI:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2.4.0

      - name: README CI
        uses: Tarang74/test-readme-actions@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
