name: Continuous Integration Workflow

on:
  push:
    branches: [master]

jobs:
  README-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: README CI
        uses: 'Tarang74/readme-ci@master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
