name: Continuous Integration Workflow

on:
  push:
    branches: [master]

jobs:
  README-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: README CI
        uses: Tarang74/test-readme-actions@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
