name: Continuous Integration Workflow

on:
  push:
    branches: [master]

jobs:
  README-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true

      - name: README CI
        uses: "lib/index.js"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
