name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  Generate-README:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup actions with pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          run_install: true

      # - name: Echo directory contents
      #   run: ls -R -I node_modules
        
      - name: Update README
        uses: ~/action.yml
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}